name: "cloudfront-invalidate-caches"
description: "Invalidate caches for AWS cloudfront distribution"
inputs:
  cloudfront-distribution-id:
    description: "The Id of a cloudfront distribution"
    required: true
  cloudfront-invalidation-path:
    description: "Path to invalidate in the cloudfront distribution"
    required: true
    default: /*
outputs:
  invalidation-id:
    description: 'The ID of invalidation caches created.'
runs:
  using: 'docker'
  main: 'Dockerfile'
branding:
  icon: cloud
  color: blue