name: "cloudfront-invalidate-caches"
description: "Invalidate caches for AWS cloudfront distribution"
inputs:
  cloudfront-distribution-id:
    description: "The Id of a cloudfront distribution"
    required: true
  cloudfront-invalidation-path:
    description: "Path to invalidate in the cloudfront distribution"
    required: true
    default: /*
runs:
  using: "composite"
  steps:
  - shell: bash
    run: | 
      pip install -r $GITHUB_ACTION_PATH/requirements.txt
      python $GITHUB_ACTION_PATH/main.py ${{ inputs.cloudfront-distribution-id }} "${{ inputs.invalidation-paths }}"
branding:
  icon: cloud
  color: blue