name: "cloudfront-invalidate-caches"
description: "Invalidate caches for AWS cloudfront distribution"
inputs:
  cloudfront-distribution-id:
    description: "The Id of a cloudfront distribution"
    required: true
  cloudfront-invalidation-path:
    description: "Path to invalidate in the cloudfront distribution"
    required: true
    default: /*
outputs:
  invalidation_id:
    description: "This output reffers to the invalidation id created in AWS Cloudfront"
    value: ${{ steps.python-run.outputs.invalidation_id }}
runs:
  using: "composite"
  steps:
  - shell: bash
    id: python-run
    run: | 
      pip install -r $GITHUB_ACTION_PATH/requirements.txt
      python $GITHUB_ACTION_PATH/main.py ${{ inputs.cloudfront-distribution-id }} "${{ inputs.invalidation-paths }}"
      echo $INVALIDATION_ID
branding:
  icon: cloud
  color: blue