name: "cloudfront-invalidate-caches"
description: "Invalidate caches for AWS cloudfront distribution"
inputs:
  cloudfront-distribution-id:
    description: "The Id of a cloudfront distribution"
    required: true
  cloudfront-invalidation-path:
    description: "Path to invalidate in the cloudfront distribution"
    required: true
    default: /*
runs:
  using: "composite"
  steps:
  - shell: bash
    run: python $GITHUB_ACTION_PATH/main.py
branding:
  icon: cloud
  color: blue